name=["Мексика","Австралия","Канада","Финляндия","Венгрия"]
print(sorted(name))
print(name)
print(sorted(name,reverse=True))
print(name)
name.reverse()
print(name)
name.reverse()
print(name)
name.sort()
print(name)
name.sort(reverse=True)
print(name)
print(len(name))
#name.reverse()
#print("\nЭто измененный список: ")
#print(name[0].title())
#print(len(name))